global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@datavault.pro'
  smtp_auth_username: 'alerts@datavault.pro'
  smtp_auth_password: 'your-smtp-password'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'default-receiver'
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 10s
      repeat_interval: 5m

    # Warning alerts - grouped notification
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 1m
      repeat_interval: 30m

    # Service-specific routing
    - match:
        service: datavault-app
      receiver: 'app-team'

    - match:
        service: scraper
      receiver: 'scraper-team'

    - match:
        service: security
      receiver: 'security-team'
      group_wait: 0s
      repeat_interval: 1m

inhibit_rules:
  # Inhibit warning alerts if critical alert for same service is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['service', 'instance']

  # Inhibit duplicate alerts
  - source_match:
      alertname: 'DataVaultDown'
    target_match_re:
      alertname: '.*High.*'
    equal: ['instance']

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'devops@datavault.pro'
        subject: 'DataVault Pro Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          {{ end }}

  - name: 'critical-alerts'
    email_configs:
      - to: 'oncall@datavault.pro, devops@datavault.pro'
        subject: 'CRITICAL: DataVault Pro Alert'
        body: |
          🚨 CRITICAL ALERT 🚨

          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05" }}

          {{ end }}

          Please investigate immediately!
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts-critical'
        title: '🚨 CRITICAL: DataVault Pro Alert'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Service:* {{ .Labels.service }}
          *Instance:* {{ .Labels.instance }}
          {{ end }}
    webhook_configs:
      - url: 'http://host.docker.internal:3000/api/alerts/webhook'
        send_resolved: true

  - name: 'warning-alerts'
    email_configs:
      - to: 'devops@datavault.pro'
        subject: 'WARNING: DataVault Pro Alert'
        body: |
          ⚠️  WARNING ALERT ⚠️

          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05" }}

          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts-warning'
        title: '⚠️ WARNING: DataVault Pro Alert'

  - name: 'app-team'
    email_configs:
      - to: 'app-team@datavault.pro'
        subject: 'App Alert: {{ .GroupLabels.alertname }}'
        body: |
          Application Alert Details:
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}

  - name: 'scraper-team'
    email_configs:
      - to: 'scraper-team@datavault.pro'
        subject: 'Scraper Alert: {{ .GroupLabels.alertname }}'
        body: |
          Scraper Service Alert:
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}

  - name: 'security-team'
    email_configs:
      - to: 'security@datavault.pro, oncall@datavault.pro'
        subject: 'SECURITY ALERT: {{ .GroupLabels.alertname }}'
        body: |
          🔒 SECURITY ALERT 🔒

          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

          Immediate investigation required!
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#security-alerts'
        title: '🔒 SECURITY ALERT'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          {{ end }}

templates:
  - '/etc/alertmanager/templates/*.tmpl'
